export default [
  {
    "_id": "Q101",
    "course": "RS101",
    "user": "faculty001",
    "questions": ["QU101", "QU102", "QU103"],
    "title": "Propulsion Fundamentals Quiz",
    "description": "<p>Test your knowledge of basic propulsion principles and rocket engine fundamentals.</p>",
    "quiz_type": "graded_quiz",
    "points": 30,
    "assignment_group": "quizzes",
    "published": true,
    "shuffle_answers": true,
    "time_limit": 20,
    "multiple_attempts": false,
    "show_correct_answers": "after_due_date",
    "access_code": "",
    "one_question_at_time": true,
    "webcam_required": false,
    "lock_questions_after_answering": false,
    "due_date": "2025-03-15T23:59:00Z",
    "available_date": "2025-03-01T00:00:00Z",
    "available_until": "2025-03-16T23:59:00Z"
  },
  {
    "_id": "Q102",
    "course": "RS101",
    "user": "faculty001",
    "questions": ["QU104", "QU105"],
    "title": "Combustion Chamber Design",
    "description": "<p>Assessment covering combustion chamber design principles and thermal analysis.</p>",
    "quiz_type": "graded_quiz",
    "points": 20,
    "assignment_group": "exams",
    "published": false,
    "shuffle_answers": true,
    "time_limit": 30,
    "multiple_attempts": true,
    "show_correct_answers": "never",
    "access_code": "ROCKET123",
    "one_question_at_time": false,
    "webcam_required": true,
    "lock_questions_after_answering": true,
    "due_date": "2025-04-01T23:59:00Z",
    "available_date": "2025-03-20T00:00:00Z",
    "available_until": "2025-04-02T23:59:00Z"
  },
  {
    "_id": "Q103",
    "course": "RS101",
    "user": "faculty001",
    "questions": ["QU106"],
    "title": "Nozzle Performance Survey",
    "description": "<p>Quick survey about nozzle design preferences and understanding.</p>",
    "quiz_type": "ungraded_survey",
    "points": 0,
    "assignment_group": "assignments",
    "published": true,
    "shuffle_answers": false,
    "time_limit": 10,
    "multiple_attempts": false,
    "show_correct_answers": "immediately",
    "access_code": "",
    "one_question_at_time": true,
    "webcam_required": false,
    "lock_questions_after_answering": false,
    "due_date": "2025-05-15T23:59:00Z",
    "available_date": "2025-05-01T00:00:00Z",
    "available_until": "2025-05-16T23:59:00Z"
  },
  {
    "_id": "Q201",
    "course": "RS102",
    "user": "faculty002",
    "questions": ["QU201", "QU202", "QU203", "QU204"],
    "title": "Aerodynamics Principles Test",
    "description": "<p>Comprehensive test on aerodynamic principles, lift, drag, and flow characteristics.</p>",
    "quiz_type": "graded_quiz",
    "points": 40,
    "assignment_group": "quizzes",
    "published": true,
    "shuffle_answers": true,
    "time_limit": 25,
    "multiple_attempts": false,
    "show_correct_answers": "after_last_attempt",
    "access_code": "",
    "one_question_at_time": true,
    "webcam_required": false,
    "lock_questions_after_answering": false,
    "due_date": "2025-03-20T23:59:00Z",
    "available_date": "2025-03-05T00:00:00Z",
    "available_until": "2025-03-21T23:59:00Z"
  },
  {
    "_id": "Q202",
    "course": "RS102",
    "user": "faculty002",
    "questions": ["QU205", "QU206"],
    "title": "Flow Analysis Practice",
    "description": "<p>Practice quiz for flow analysis techniques and computational methods.</p>",
    "quiz_type": "practice_quiz",
    "points": 15,
    "assignment_group": "quizzes",
    "published": false,
    "shuffle_answers": true,
    "time_limit": 15,
    "multiple_attempts": true,
    "show_correct_answers": "immediately",
    "access_code": "",
    "one_question_at_time": false,
    "webcam_required": false,
    "lock_questions_after_answering": false,
    "due_date": "2025-04-10T23:59:00Z",
    "available_date": "2025-03-25T00:00:00Z",
    "available_until": "2025-04-11T23:59:00Z"
  },
  {
    "_id": "Q203",
    "course": "RS102",
    "user": "faculty002",
    "questions": ["QU207", "QU208", "QU209"],
    "title": "Heat Transfer Mechanisms",
    "description": "<p>Graded assessment on heat transfer in aerospace applications.</p>",
    "quiz_type": "graded_survey",
    "points": 25,
    "assignment_group": "exams",
    "published": true,
    "shuffle_answers": false,
    "time_limit": 35,
    "multiple_attempts": false,
    "show_correct_answers": "after_due_date",
    "access_code": "HEAT456",
    "one_question_at_time": true,
    "webcam_required": true,
    "lock_questions_after_answering": true,
    "due_date": "2025-04-25T23:59:00Z",
    "available_date": "2025-04-15T00:00:00Z",
    "available_until": "2025-04-26T23:59:00Z"
  },
  {
    "_id": "Q301",
    "course": "RS103",
    "user": "faculty003",
    "questions": ["QU301", "QU302", "QU303", "QU304"],
    "title": "Spacecraft Structures Quiz",
    "description": "<p>Test covering spacecraft structural design, materials, and load analysis.</p>",
    "quiz_type": "graded_quiz",
    "points": 35,
    "assignment_group": "quizzes",
    "published": true,
    "shuffle_answers": true,
    "time_limit": 30,
    "multiple_attempts": false,
    "show_correct_answers": "after_due_date",
    "access_code": "",
    "one_question_at_time": true,
    "webcam_required": false,
    "lock_questions_after_answering": false,
    "due_date": "2025-03-30T23:59:00Z",
    "available_date": "2025-03-15T00:00:00Z",
    "available_until": "2025-03-31T23:59:00Z"
  },
  {
    "_id": "Q302",
    "course": "RS103",
    "user": "faculty003",
    "questions": ["QU305", "QU306"],
    "title": "Orbital Mechanics Midterm",
    "description": "<p>Comprehensive midterm examination on orbital mechanics and spacecraft trajectories.</p>",
    "quiz_type": "graded_quiz",
    "points": 50,
    "assignment_group": "exams",
    "published": false,
    "shuffle_answers": true,
    "time_limit": 60,
    "multiple_attempts": false,
    "show_correct_answers": "never",
    "access_code": "ORBIT789",
    "one_question_at_time": true,
    "webcam_required": true,
    "lock_questions_after_answering": true,
    "due_date": "2025-04-15T23:59:00Z",
    "available_date": "2025-04-15T08:00:00Z",
    "available_until": "2025-04-15T23:59:00Z"
  },
  {
    "_id": "Q303",
    "course": "RS103",
    "user": "faculty003",
    "questions": ["QU307", "QU308", "QU309"],
    "title": "Systems Integration Check",
    "description": "<p>Quick assessment of systems engineering integration concepts and methodologies.</p>",
    "quiz_type": "practice_quiz",
    "points": 18,
    "assignment_group": "project",
    "published": true,
    "shuffle_answers": false,
    "time_limit": 20,
    "multiple_attempts": true,
    "show_correct_answers": "immediately",
    "access_code": "",
    "one_question_at_time": false,
    "webcam_required": false,
    "lock_questions_after_answering": false,
    "due_date": "2025-05-30T23:59:00Z",
    "available_date": "2025-05-15T00:00:00Z",
    "available_until": "2025-05-31T23:59:00Z"
  }
]